name: Cypress Tests

on:
  push:
    branches: 
    - main
    - dev/client/client_main
    - dev/dev_main
  pull_request:
    branches: 
    - main
    - dev/client/client_main
    - dev/dev_main

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        start: docker-compose up -d
        working-directory: ./client