name: Cypress Tests

on:
  push:
    branches: 
    - main
    - dev/client/client_main
    - dev/dev_main
  pull_request:
    branches: 
    - main
    - dev/client/client_main
    - dev/dev_main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start Postgres
      run: docker-compose up -d postgres

    - name: Seed database
      run: |
        cd api
        npm install
        npx prisma db push
        node prisma/seed.js

    - name: Start Express
      run: docker-compose up -d express

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        working-directory: ./client
        start: npm start
      