# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - main
      - dev/client/client_main
      - dev/dev_main
  pull_request:
    branches: 
      - main
      - dev/client/client_main
      - dev/dev_main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker-compose up -d postgress
      working-directory: .
    - name: Install dependencies and start express server
      run: |
        cd api
        npm install
        npm run dev
      working-directory: .
    - name: Install dependencies and run tests
      run: |
        cd client
        npm install
        npm run test
      working-directory: .
#     - run: |
#         pkill node
#       working-directory: ./api
#     - run: docker-compose down
#       working-directory: .
