# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
    - main
    - dev/client/client_main
    - dev/dev_main
  pull_request:
    branches: 
    - main
    - dev/client/client_main
    - dev/dev_main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: pwd
    - run: ls -hartl
    - run: cd TeamTeam-BookingApp
    - run: ls -hartl